nexus_info:
  Repositories:
    - file: yum-proxy.json
      type: proxy
      format: yum

    - name: epel-yum-proxy.json
      type: proxy
      format: yum

    - name: ius-yum-proxy.json
      type: proxy
      format: yum

    - name: pypi-proxy.json
      type: proxy
      format: pypi

    - name: maven-proxy.json
      type: proxy
      format: maven

    - name: docker-proxy.json
      type: proxy
      format: docker

    - name: docker-hosted.json
      type: hosted
      format: docker

    - name: docker-group.json
      type: group
      format: docker
