- hosts: node1
  tasks:
    - name: Insert/Update HTML surrounded by custom markers after <body> line
      ansible.builtin.blockinfile:
        path: /tmp/index.html
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        insertafter: "<body>"
        block: |
          <h1>Welcome to {{ ansible_hostname }}</h1>
          <p>Last updated on {{ ansible_date_time.iso8601 }}</p>
        create: yes

    - name: Insert/Update block by custom markers in /tmp/sshd_config
      ansible.builtin.blockinfile:
        path: /tmp/sshd_config
        block: |
          iface eth0 inet static
              address 192.0.2.23
                netmask 255.255.255.0
        marker: "# meizhaohui add this block {mark}"
        marker_begin: ' start ==>'
        marker_end: ' end <=='
        create: yes
        state: present
      become: yes

    - name: Remove block in /tmp/sshd_config
      ansible.builtin.blockinfile:
        path: /tmp/sshd_config
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: ""
        state: present
      become: yes

    - name: Insert/Update "Match User" configuration block in /tmp/sshd_config
      ansible.builtin.blockinfile:
        path: /tmp/sshd_config
        block: |
          Match User ansible-agent
          PasswordAuthentication no
        create: yes
        state: present
      become: yes
