---
- hosts: node1
  # 定义变量
  vars:
    - nginx_path: "/etc/nginx/*.conf"

  tasks:
    - name: find nginx conf files
      ansible.builtin.debug:
        msg: |
          The config file list is {{ nginx_path|fileglob }}
