---
- hosts: node1
  # 定义变量
  vars:
    - config_path: "/srv/tomcat/apache-tomcat-9.0.73/conf/server.xml"

  tasks:
    - name: display the filename root and extension
      ansible.builtin.debug:
        msg: |
          The config path is {{ config_path }}
          The filename root and extension list is {{ config_path|ansible.builtin.splitext }}
