---
- hosts: node1

  tasks:
    - name: debug lookups ini file
      ansible.builtin.debug:
        msg: |
          User in integration is {{ lookup('ini', 'user section=integration file=users.ini') }}".
          User in production  is {{ lookup('ini', 'user section=production  file=users.ini') }}.
