- hosts: node1
  tasks:
    - name: use with_items
      ansible.builtin.debug:
        msg: "The number is: {{ item }}"
      with_items:
        - 1
        - [2,3]
        - 4
        - [[5,6],[7,8]]

    - name: use loop with flatten one level
      ansible.builtin.debug:
        msg: "The number is: {{ item }}"
      loop: "{{ [1, [2, 3], 4, [[5,6],[7,8]]] | flatten(1) }}"

    - name: use loop with flatten two level
      ansible.builtin.debug:
        msg: "The number is: {{ item }}"
      loop: "{{ [1, [2, 3], 4, [[5,6],[7,8]]] | flatten(2) }}"

    - name: use loop flatten
      ansible.builtin.debug:
        msg: "The number is: {{ item }}"
      loop: "{{ [1, [2, 3], 4, [[5,6],[7,8]]]|flatten }}"