- hosts: node1
  tasks:
    - name: Template configuration file 1
      ansible.builtin.template:
        src: handlers_template.j2
        dest: /etc/handlers_1.conf
      # notify接受触发器任务名称列表
      notify:
        - Restart nginx
        - Restart memcached
      become: yes

    - name: Template configuration file 2
      ansible.builtin.template:
        src: handlers_template.j2
        dest: /etc/handlers_2.conf
      # notify接受触发器任务名称字符串
      notify: Restart nginx
      become: yes

  handlers:
    - name: Restart memcached
      ansible.builtin.service:
        name: memcached
        state: restarted
      become: yes

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: yes
