---
- hosts: node1
  tasks:
    - name: register variable
      ansible.builtin.command:
        cmd: hostname
      register: info

    - name: display variable
      ansible.builtin.debug:
        msg: The variable is {{ info['stdout'] }}
